import { Influencer } from "@/types/leaderboard";

export const dummyInfluencers: Influencer[] = [
  {
    id: "1",
    rank: 1,
    name: "John Doe",
    score: 95,
    trend: "up",
    followers: 1000000,
    verifiedClaims: 150,
    avatar: "",
    category: ["sleep", "performance", "hormones", "nutrition"],
    verificationStatus: "Verified",
    yearlyRevenue: 500000,
    bio: "John is a leading expert in optimizing sleep and performance. With over a decade of experience, he has helped millions of followers worldwide achieve their health and wellness goals through science-backed strategies. His expertise spans improving hormonal balance, enhancing athletic performance, and adopting sustainable nutritional practices for long-term health.",
  },
  {
    id: "2",
    rank: 2,
    name: "Jane Smith",
    score: 89,
    trend: "down",
    followers: 800000,
    verifiedClaims: 120,
    avatar: "",
    category: ["fitness", "wellness", "nutrition"],
    verificationStatus: "Questionable",
    yearlyRevenue: 300000,
    bio: "Certified fitness trainer sharing nutrition and wellness tips to stay fit.",
  },
  {
    id: "3",
    rank: 3,
    name: "Emily Johnson",
    score: 75,
    trend: "neutral",
    followers: 600000,
    verifiedClaims: 95,
    avatar: "",
    category: ["mental health", "sleep", "stress management"],
    verificationStatus: "Debunked",
    yearlyRevenue: 200000,
    bio: "Certified fitness trainer sharing nutrition and wellness tips to stay fit.",
  },
  {
    id: "4",
    rank: 4,
    name: "Michael Brown",
    score: 82,
    trend: "up",
    followers: 500000,
    verifiedClaims: 110,
    avatar: "",
    category: ["medical science", "nutrition"],
    verificationStatus: "Verified",
    yearlyRevenue: 400000,
    bio: "Certified fitness trainer sharing nutrition and wellness tips to stay fit.",
  },
  {
    id: "5",
    rank: 5,
    name: "Sarah Wilson",
    score: 70,
    trend: "down",
    followers: 400000,
    verifiedClaims: 80,
    avatar: "",
    category: ["lifestyle", "fitness", "wellness"],
    verificationStatus: "Questionable",
    yearlyRevenue: 250000,
    bio: "Certified fitness trainer sharing nutrition and wellness tips to stay fit.",
  },
];
